name: Build a dummy ROCK

on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build a ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          path: tests
          verbosity: debug
      - name: Upload ROCK
        uses: actions/upload-artifact@v3
        with:
          name: dummy-rock
          path: ${{ steps.rockcraft.outputs.rock }}

